-- GENERADO por tests/local/gen_revoke_anon_tablas.py — no editar a mano.
-- ROLLBACK: devuelve a anon lo que tenía el 03/10 (ALL; recibos todo menos DELETE).
BEGIN;
GRANT ALL ON TABLE public.apoderados TO anon;
GRANT ALL ON TABLE public.auditoria TO anon;
GRANT ALL ON TABLE public.caballeriza_responsables TO anon;
GRANT ALL ON TABLE public.caballerizas TO anon;
GRANT ALL ON TABLE public.carrera_apuestas TO anon;
GRANT ALL ON TABLE public.carreras TO anon;
GRANT ALL ON TABLE public.categorias_carrera TO anon;
GRANT ALL ON TABLE public.club_configuracion TO anon;
GRANT ALL ON TABLE public.club_secuencias TO anon;
GRANT ALL ON TABLE public.clubs TO anon;
GRANT ALL ON TABLE public.comision_config TO anon;
GRANT ALL ON TABLE public.hipodromos TO anon;
GRANT ALL ON TABLE public.inscripciones TO anon;
GRANT ALL ON TABLE public.liquidacion_config TO anon;
GRANT ALL ON TABLE public.liquidacion_detalle TO anon;
GRANT ALL ON TABLE public.liquidaciones TO anon;
GRANT ALL ON TABLE public.novedades_reunion TO anon;
GRANT ALL ON TABLE public.performances TO anon;
GRANT ALL ON TABLE public.profesionales TO anon;
GRANT ALL ON TABLE public.propietarios TO anon;
GRANT ALL ON TABLE public.recibos TO anon;
REVOKE DELETE ON TABLE public.recibos FROM anon;
GRANT ALL ON TABLE public.resolucion_entidades TO anon;
GRANT ALL ON TABLE public.resoluciones TO anon;
GRANT ALL ON TABLE public.resultado_apuestas TO anon;
GRANT ALL ON TABLE public.resultado_log TO anon;
GRANT ALL ON TABLE public.resultado_posiciones TO anon;
GRANT ALL ON TABLE public.resultados TO anon;
GRANT ALL ON TABLE public.reuniones TO anon;
GRANT ALL ON TABLE public.sanciones TO anon;
GRANT ALL ON TABLE public.solicitudes_acceso TO anon;
GRANT ALL ON TABLE public.spc_entrenadores_hist TO anon;
GRANT ALL ON TABLE public.spc_propietarios TO anon;
GRANT ALL ON TABLE public.spcs TO anon;
GRANT ALL ON TABLE public.usuarios TO anon;
GRANT ALL ON TABLE public.v_programa_reunion TO anon;
GRANT ALL ON TABLE public.v_sanciones_vigentes TO anon;
GRANT ALL ON TABLE public.v_spcs_activos TO anon;
COMMIT;
