-- GENERADO por tests/local/gen_revoke_anon_tablas.py — no editar a mano.
-- Sandbox: stubs de lo que no existe en `sgh` + ACL de anon como prod (ALL; recibos sin DELETE).
DO $$ BEGIN IF to_regclass('public.apoderados') IS NULL THEN EXECUTE 'CREATE TABLE public.apoderados (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), dato text)'; EXECUTE 'ALTER TABLE public.apoderados ENABLE ROW LEVEL SECURITY'; EXECUTE 'INSERT INTO public.apoderados(dato) VALUES (''x'')'; END IF; END $$;
DO $$ BEGIN IF to_regclass('public.auditoria') IS NULL THEN EXECUTE 'CREATE TABLE public.auditoria (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), dato text)'; EXECUTE 'ALTER TABLE public.auditoria ENABLE ROW LEVEL SECURITY'; EXECUTE 'INSERT INTO public.auditoria(dato) VALUES (''x'')'; END IF; END $$;
DO $$ BEGIN IF to_regclass('public.caballeriza_responsables') IS NULL THEN EXECUTE 'CREATE TABLE public.caballeriza_responsables (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), dato text)'; EXECUTE 'ALTER TABLE public.caballeriza_responsables ENABLE ROW LEVEL SECURITY'; EXECUTE 'INSERT INTO public.caballeriza_responsables(dato) VALUES (''x'')'; END IF; END $$;
DO $$ BEGIN IF to_regclass('public.caballerizas') IS NULL THEN EXECUTE 'CREATE TABLE public.caballerizas (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), dato text)'; EXECUTE 'ALTER TABLE public.caballerizas ENABLE ROW LEVEL SECURITY'; EXECUTE 'INSERT INTO public.caballerizas(dato) VALUES (''x'')'; END IF; END $$;
DO $$ BEGIN IF to_regclass('public.carrera_apuestas') IS NULL THEN EXECUTE 'CREATE TABLE public.carrera_apuestas (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), dato text)'; EXECUTE 'ALTER TABLE public.carrera_apuestas ENABLE ROW LEVEL SECURITY'; EXECUTE 'INSERT INTO public.carrera_apuestas(dato) VALUES (''x'')'; END IF; END $$;
DO $$ BEGIN IF to_regclass('public.carreras') IS NULL THEN EXECUTE 'CREATE TABLE public.carreras (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), dato text)'; EXECUTE 'ALTER TABLE public.carreras ENABLE ROW LEVEL SECURITY'; EXECUTE 'INSERT INTO public.carreras(dato) VALUES (''x'')'; END IF; END $$;
DO $$ BEGIN IF to_regclass('public.categorias_carrera') IS NULL THEN EXECUTE 'CREATE TABLE public.categorias_carrera (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), dato text)'; EXECUTE 'ALTER TABLE public.categorias_carrera ENABLE ROW LEVEL SECURITY'; EXECUTE 'INSERT INTO public.categorias_carrera(dato) VALUES (''x'')'; END IF; END $$;
DO $$ BEGIN IF to_regclass('public.club_configuracion') IS NULL THEN EXECUTE 'CREATE TABLE public.club_configuracion (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), dato text)'; EXECUTE 'ALTER TABLE public.club_configuracion ENABLE ROW LEVEL SECURITY'; EXECUTE 'INSERT INTO public.club_configuracion(dato) VALUES (''x'')'; END IF; END $$;
DO $$ BEGIN IF to_regclass('public.club_secuencias') IS NULL THEN EXECUTE 'CREATE TABLE public.club_secuencias (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), dato text)'; EXECUTE 'ALTER TABLE public.club_secuencias ENABLE ROW LEVEL SECURITY'; EXECUTE 'INSERT INTO public.club_secuencias(dato) VALUES (''x'')'; END IF; END $$;
DO $$ BEGIN IF to_regclass('public.clubs') IS NULL THEN EXECUTE 'CREATE TABLE public.clubs (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), dato text)'; EXECUTE 'ALTER TABLE public.clubs ENABLE ROW LEVEL SECURITY'; EXECUTE 'INSERT INTO public.clubs(dato) VALUES (''x'')'; END IF; END $$;
DO $$ BEGIN IF to_regclass('public.comision_config') IS NULL THEN EXECUTE 'CREATE TABLE public.comision_config (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), dato text)'; EXECUTE 'ALTER TABLE public.comision_config ENABLE ROW LEVEL SECURITY'; EXECUTE 'INSERT INTO public.comision_config(dato) VALUES (''x'')'; END IF; END $$;
DO $$ BEGIN IF to_regclass('public.hipodromos') IS NULL THEN EXECUTE 'CREATE TABLE public.hipodromos (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), dato text)'; EXECUTE 'ALTER TABLE public.hipodromos ENABLE ROW LEVEL SECURITY'; EXECUTE 'INSERT INTO public.hipodromos(dato) VALUES (''x'')'; END IF; END $$;
DO $$ BEGIN IF to_regclass('public.inscripciones') IS NULL THEN EXECUTE 'CREATE TABLE public.inscripciones (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), dato text)'; EXECUTE 'ALTER TABLE public.inscripciones ENABLE ROW LEVEL SECURITY'; EXECUTE 'INSERT INTO public.inscripciones(dato) VALUES (''x'')'; END IF; END $$;
DO $$ BEGIN IF to_regclass('public.liquidacion_config') IS NULL THEN EXECUTE 'CREATE TABLE public.liquidacion_config (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), dato text)'; EXECUTE 'ALTER TABLE public.liquidacion_config ENABLE ROW LEVEL SECURITY'; EXECUTE 'INSERT INTO public.liquidacion_config(dato) VALUES (''x'')'; END IF; END $$;
DO $$ BEGIN IF to_regclass('public.liquidacion_detalle') IS NULL THEN EXECUTE 'CREATE TABLE public.liquidacion_detalle (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), dato text)'; EXECUTE 'ALTER TABLE public.liquidacion_detalle ENABLE ROW LEVEL SECURITY'; EXECUTE 'INSERT INTO public.liquidacion_detalle(dato) VALUES (''x'')'; END IF; END $$;
DO $$ BEGIN IF to_regclass('public.liquidaciones') IS NULL THEN EXECUTE 'CREATE TABLE public.liquidaciones (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), dato text)'; EXECUTE 'ALTER TABLE public.liquidaciones ENABLE ROW LEVEL SECURITY'; EXECUTE 'INSERT INTO public.liquidaciones(dato) VALUES (''x'')'; END IF; END $$;
DO $$ BEGIN IF to_regclass('public.novedades_reunion') IS NULL THEN EXECUTE 'CREATE TABLE public.novedades_reunion (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), dato text)'; EXECUTE 'ALTER TABLE public.novedades_reunion ENABLE ROW LEVEL SECURITY'; EXECUTE 'INSERT INTO public.novedades_reunion(dato) VALUES (''x'')'; END IF; END $$;
DO $$ BEGIN IF to_regclass('public.performances') IS NULL THEN EXECUTE 'CREATE TABLE public.performances (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), dato text)'; EXECUTE 'ALTER TABLE public.performances ENABLE ROW LEVEL SECURITY'; EXECUTE 'INSERT INTO public.performances(dato) VALUES (''x'')'; END IF; END $$;
DO $$ BEGIN IF to_regclass('public.profesionales') IS NULL THEN EXECUTE 'CREATE TABLE public.profesionales (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), dato text)'; EXECUTE 'ALTER TABLE public.profesionales ENABLE ROW LEVEL SECURITY'; EXECUTE 'INSERT INTO public.profesionales(dato) VALUES (''x'')'; END IF; END $$;
DO $$ BEGIN IF to_regclass('public.propietarios') IS NULL THEN EXECUTE 'CREATE TABLE public.propietarios (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), dato text)'; EXECUTE 'ALTER TABLE public.propietarios ENABLE ROW LEVEL SECURITY'; EXECUTE 'INSERT INTO public.propietarios(dato) VALUES (''x'')'; END IF; END $$;
DO $$ BEGIN IF to_regclass('public.recibos') IS NULL THEN EXECUTE 'CREATE TABLE public.recibos (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), dato text)'; EXECUTE 'ALTER TABLE public.recibos ENABLE ROW LEVEL SECURITY'; EXECUTE 'INSERT INTO public.recibos(dato) VALUES (''x'')'; END IF; END $$;
DO $$ BEGIN IF to_regclass('public.resolucion_entidades') IS NULL THEN EXECUTE 'CREATE TABLE public.resolucion_entidades (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), dato text)'; EXECUTE 'ALTER TABLE public.resolucion_entidades ENABLE ROW LEVEL SECURITY'; EXECUTE 'INSERT INTO public.resolucion_entidades(dato) VALUES (''x'')'; END IF; END $$;
DO $$ BEGIN IF to_regclass('public.resoluciones') IS NULL THEN EXECUTE 'CREATE TABLE public.resoluciones (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), dato text)'; EXECUTE 'ALTER TABLE public.resoluciones ENABLE ROW LEVEL SECURITY'; EXECUTE 'INSERT INTO public.resoluciones(dato) VALUES (''x'')'; END IF; END $$;
DO $$ BEGIN IF to_regclass('public.resultado_apuestas') IS NULL THEN EXECUTE 'CREATE TABLE public.resultado_apuestas (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), dato text)'; EXECUTE 'ALTER TABLE public.resultado_apuestas ENABLE ROW LEVEL SECURITY'; EXECUTE 'INSERT INTO public.resultado_apuestas(dato) VALUES (''x'')'; END IF; END $$;
DO $$ BEGIN IF to_regclass('public.resultado_log') IS NULL THEN EXECUTE 'CREATE TABLE public.resultado_log (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), dato text)'; EXECUTE 'ALTER TABLE public.resultado_log ENABLE ROW LEVEL SECURITY'; EXECUTE 'INSERT INTO public.resultado_log(dato) VALUES (''x'')'; END IF; END $$;
DO $$ BEGIN IF to_regclass('public.resultado_posiciones') IS NULL THEN EXECUTE 'CREATE TABLE public.resultado_posiciones (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), dato text)'; EXECUTE 'ALTER TABLE public.resultado_posiciones ENABLE ROW LEVEL SECURITY'; EXECUTE 'INSERT INTO public.resultado_posiciones(dato) VALUES (''x'')'; END IF; END $$;
DO $$ BEGIN IF to_regclass('public.resultados') IS NULL THEN EXECUTE 'CREATE TABLE public.resultados (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), dato text)'; EXECUTE 'ALTER TABLE public.resultados ENABLE ROW LEVEL SECURITY'; EXECUTE 'INSERT INTO public.resultados(dato) VALUES (''x'')'; END IF; END $$;
DO $$ BEGIN IF to_regclass('public.reuniones') IS NULL THEN EXECUTE 'CREATE TABLE public.reuniones (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), dato text)'; EXECUTE 'ALTER TABLE public.reuniones ENABLE ROW LEVEL SECURITY'; EXECUTE 'INSERT INTO public.reuniones(dato) VALUES (''x'')'; END IF; END $$;
DO $$ BEGIN IF to_regclass('public.sanciones') IS NULL THEN EXECUTE 'CREATE TABLE public.sanciones (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), dato text)'; EXECUTE 'ALTER TABLE public.sanciones ENABLE ROW LEVEL SECURITY'; EXECUTE 'INSERT INTO public.sanciones(dato) VALUES (''x'')'; END IF; END $$;
DO $$ BEGIN IF to_regclass('public.solicitudes_acceso') IS NULL THEN EXECUTE 'CREATE TABLE public.solicitudes_acceso (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), dato text)'; EXECUTE 'ALTER TABLE public.solicitudes_acceso ENABLE ROW LEVEL SECURITY'; EXECUTE 'INSERT INTO public.solicitudes_acceso(dato) VALUES (''x'')'; END IF; END $$;
DO $$ BEGIN IF to_regclass('public.spc_entrenadores_hist') IS NULL THEN EXECUTE 'CREATE TABLE public.spc_entrenadores_hist (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), dato text)'; EXECUTE 'ALTER TABLE public.spc_entrenadores_hist ENABLE ROW LEVEL SECURITY'; EXECUTE 'INSERT INTO public.spc_entrenadores_hist(dato) VALUES (''x'')'; END IF; END $$;
DO $$ BEGIN IF to_regclass('public.spc_propietarios') IS NULL THEN EXECUTE 'CREATE TABLE public.spc_propietarios (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), dato text)'; EXECUTE 'ALTER TABLE public.spc_propietarios ENABLE ROW LEVEL SECURITY'; EXECUTE 'INSERT INTO public.spc_propietarios(dato) VALUES (''x'')'; END IF; END $$;
DO $$ BEGIN IF to_regclass('public.spcs') IS NULL THEN EXECUTE 'CREATE TABLE public.spcs (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), dato text)'; EXECUTE 'ALTER TABLE public.spcs ENABLE ROW LEVEL SECURITY'; EXECUTE 'INSERT INTO public.spcs(dato) VALUES (''x'')'; END IF; END $$;
DO $$ BEGIN IF to_regclass('public.usuarios') IS NULL THEN EXECUTE 'CREATE TABLE public.usuarios (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), dato text)'; EXECUTE 'ALTER TABLE public.usuarios ENABLE ROW LEVEL SECURITY'; EXECUTE 'INSERT INTO public.usuarios(dato) VALUES (''x'')'; END IF; END $$;
DO $$ BEGIN IF to_regclass('public.v_programa_reunion') IS NULL THEN EXECUTE 'CREATE VIEW public.v_programa_reunion WITH (security_invoker = true) AS SELECT id FROM public.reuniones'; END IF; END $$;
DO $$ BEGIN IF to_regclass('public.v_sanciones_vigentes') IS NULL THEN EXECUTE 'CREATE VIEW public.v_sanciones_vigentes WITH (security_invoker = true) AS SELECT id FROM public.reuniones'; END IF; END $$;
DO $$ BEGIN IF to_regclass('public.v_spcs_activos') IS NULL THEN EXECUTE 'CREATE VIEW public.v_spcs_activos WITH (security_invoker = true) AS SELECT id FROM public.reuniones'; END IF; END $$;
GRANT ALL ON TABLE public.apoderados TO anon, authenticated, service_role;
GRANT ALL ON TABLE public.auditoria TO anon, authenticated, service_role;
GRANT ALL ON TABLE public.caballeriza_responsables TO anon, authenticated, service_role;
GRANT ALL ON TABLE public.caballerizas TO anon, authenticated, service_role;
GRANT ALL ON TABLE public.carrera_apuestas TO anon, authenticated, service_role;
GRANT ALL ON TABLE public.carreras TO anon, authenticated, service_role;
GRANT ALL ON TABLE public.categorias_carrera TO anon, authenticated, service_role;
GRANT ALL ON TABLE public.club_configuracion TO anon, authenticated, service_role;
GRANT ALL ON TABLE public.club_secuencias TO anon, authenticated, service_role;
GRANT ALL ON TABLE public.clubs TO anon, authenticated, service_role;
GRANT ALL ON TABLE public.comision_config TO anon, authenticated, service_role;
GRANT ALL ON TABLE public.hipodromos TO anon, authenticated, service_role;
GRANT ALL ON TABLE public.inscripciones TO anon, authenticated, service_role;
GRANT ALL ON TABLE public.liquidacion_config TO anon, authenticated, service_role;
GRANT ALL ON TABLE public.liquidacion_detalle TO anon, authenticated, service_role;
GRANT ALL ON TABLE public.liquidaciones TO anon, authenticated, service_role;
GRANT ALL ON TABLE public.novedades_reunion TO anon, authenticated, service_role;
GRANT ALL ON TABLE public.performances TO anon, authenticated, service_role;
GRANT ALL ON TABLE public.profesionales TO anon, authenticated, service_role;
GRANT ALL ON TABLE public.propietarios TO anon, authenticated, service_role;
GRANT ALL ON TABLE public.recibos TO anon, authenticated, service_role;
REVOKE DELETE ON TABLE public.recibos FROM anon;
GRANT ALL ON TABLE public.resolucion_entidades TO anon, authenticated, service_role;
GRANT ALL ON TABLE public.resoluciones TO anon, authenticated, service_role;
GRANT ALL ON TABLE public.resultado_apuestas TO anon, authenticated, service_role;
GRANT ALL ON TABLE public.resultado_log TO anon, authenticated, service_role;
GRANT ALL ON TABLE public.resultado_posiciones TO anon, authenticated, service_role;
GRANT ALL ON TABLE public.resultados TO anon, authenticated, service_role;
GRANT ALL ON TABLE public.reuniones TO anon, authenticated, service_role;
GRANT ALL ON TABLE public.sanciones TO anon, authenticated, service_role;
GRANT ALL ON TABLE public.solicitudes_acceso TO anon, authenticated, service_role;
GRANT ALL ON TABLE public.spc_entrenadores_hist TO anon, authenticated, service_role;
GRANT ALL ON TABLE public.spc_propietarios TO anon, authenticated, service_role;
GRANT ALL ON TABLE public.spcs TO anon, authenticated, service_role;
GRANT ALL ON TABLE public.usuarios TO anon, authenticated, service_role;
GRANT ALL ON TABLE public.v_programa_reunion TO anon, authenticated, service_role;
GRANT ALL ON TABLE public.v_sanciones_vigentes TO anon, authenticated, service_role;
GRANT ALL ON TABLE public.v_spcs_activos TO anon, authenticated, service_role;
